[package]
name = "wasmcloud-provider-cron-scheduler"
version = "0.1.0"
description = """
A capability provider template built for implementation of custom capabilities.
"""

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[badges.maintenance]
status = "actively-developed"

[dependencies]
async-nats = { workspace = true, features = ["ring"] }
bytes = { workspace = true } 
chrono = { workspace = true }
cron = "0.12"
anyhow = {workspace = true}
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
tracing = {workspace = true}
wasmcloud-provider-sdk = { workspace = true, features = ["otel"] }
wit-bindgen-wrpc = "0.9.0"