[package]
name = "wasmcloud-provider-cron-scheduler"
version = "0.1.0"
description = """
A capability provider template built for implementation of custom capabilities.
"""

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[badges.maintenance]
status = "actively-developed"

[dependencies]
async-nats = { workspace = true }
bytes = "1.5"
chrono = "0.4"
cron = "0.12"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
wasmcloud-provider-sdk = { version = "0.13.0", features = ["otel"] }
wit-bindgen-wrpc = "0.9.0"
